"""added index workspace

Revision ID: 8b2803b4c7e8
Revises: 925f1ee7a5e7
Create Date: 2026-06-06 13:20:04.228875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2803b4c7e8'
down_revision: Union[str, Sequence[str], None] = '925f1ee7a5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspace_org_slug', 'workspaces', ['organization_id', 'slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_org_slug', table_name='workspaces')
    # ### end Alembic commands ###
