"""fixed uniqness

Revision ID: 925f1ee7a5e7
Revises: 366c4d5a0ef8
Create Date: 2026-05-24 13:07:48.964094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925f1ee7a5e7'
down_revision: Union[str, Sequence[str], None] = '366c4d5a0ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['workspace_id', 'email', 'status'])
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_unique_constraint('uq_workspace_slug_per_org', 'workspaces', ['organization_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_slug_per_org', 'workspaces', type_='unique')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
